sonar.projectKey=vr1306_taskflow-be
sonar.organization=vr1306
sonar.projectName=TaskFlow Backend
sonar.projectVersion=1.0.0

# Source Code Configuration
sonar.sources=src
sonar.exclusions=**/*.test.*,**/*.spec.*,node_modules/**,coverage/**,dist/**,build/**,src/scripts/**

# Test Code Configuration
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# Coverage Configuration
sonar.coverage.exclusions=src/server.js,src/scripts/**,**/*.test.js,**/*.spec.js

# Encoding & Environment
sonar.sourceEncoding=UTF-8
sonar.javascript.environments=node
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarCloud Endpoint
sonar.host.url=https://sonarcloud.io
