sonar.projectKey=vr1306_taskflow-be
sonar.organization=vr1306
sonar.projectName=TaskFlow Backend
sonar.projectVersion=1.0.0

# Source Code Configuration
sonar.sources=src
sonar.exclusions=**/*.test.*,**/*.spec.*,node_modules/**,coverage/**,dist/**,build/**

# Encoding & Environment
sonar.sourceEncoding=UTF-8
sonar.javascript.environments=node
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarCloud Endpoint
sonar.host.url=https://sonarcloud.io
